---
# #####
# TERRAFORM LIFECYCLE MANAGED
# All changes will be overwritten
#####
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners
name : default
on :
  push :
    branches : [ "master" ]
    tags : [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request :
    types :
    - "opened"
    - "reopened"
    - "synchronize"

jobs :
  default :
    runs-on : ubuntu-latest
    steps :
    - name : checkout
      uses : "actions/checkout@v1"
    - name : npm install
      run : "npm install"
    - name : docker build raw
      run : "docker build --tag $GITHUB_REPOSITORY:$GITHUB_SHA --file ./Dockerfile ."
    - name : docker build latest
      run : "docker build --tag $GITHUB_REPOSITORY:latest --file ./Dockerfile ."
    - name : docker images all
      run : "docker images --all"
    - name : npx release
      env : { GITHUB_TOKEN : "${{ secrets.GITHUB_TOKEN }}" }
      run : "npx semantic-release"

