---
# #####
# TERRAFORM LIFECYCLE MANAGED
# All changes will be overwritten
#####
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners
name : release
on :
  push :
    branches : [ "master" ]

jobs :
  default :
    runs-on : ubuntu-latest
    steps :
    - name : checkout
      uses : "actions/checkout@v2"
    - name : npm install
      run : "npm install"
    - name : npx release
      env : { GITHUB_TOKEN : "${{ secrets.GITHUB_TOKEN }}" }
      run : "npx semantic-release"

